name: ci

on:
  push:
    branches:
      - test-private-repo

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_go_lint_test.yml@hiep/go-pull-private
    with:
      run-unit-tests: true
      run-integration-tests: true
      run-lint: true
    secrets:
      go-private-token: ${{ secrets.GO_PRIVATE_TOKEN }}

  docker_pipeline:
    uses: babylonlabs-io/.github/.github/workflows/reusable_docker_pipeline.yml@v0.1.0
    secrets: inherit
    with:
      publish: false
